"""Initial database setup with all relationships and cascade rules

Revision ID: 5b2a073c7f0d
Revises: 
Create Date: 2025-05-30 11:26:06.848592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2a073c7f0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=25), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.String(length=100), nullable=False),
    sa.Column('religion', sa.String(length=100), nullable=True),
    sa.Column('diagnosis', sa.String(length=100), nullable=True),
    sa.Column('doe', sa.String(length=100), nullable=True),
    sa.Column('precautions', sa.String(length=100), nullable=True),
    sa.Column('current_medication', sa.String(length=100), nullable=True),
    sa.Column('emergency_person', sa.String(length=100), nullable=True),
    sa.Column('contact_no', sa.String(length=100), nullable=True),
    sa.Column('alt_contact_no', sa.String(length=100), nullable=True),
    sa.Column('grade_level', sa.String(length=100), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('father_contact_no', sa.String(length=100), nullable=True),
    sa.Column('father_med_history', sa.String(length=100), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=True),
    sa.Column('mother_contact_no', sa.String(length=100), nullable=True),
    sa.Column('mother_med_history', sa.String(length=100), nullable=True),
    sa.Column('sibling', sa.String(length=100), nullable=True),
    sa.Column('sibling_med_history', sa.String(length=100), nullable=True),
    sa.Column('complication_preg', sa.String(length=100), nullable=True),
    sa.Column('med_taken', sa.String(length=100), nullable=True),
    sa.Column('duration_med_taken', sa.String(length=100), nullable=True),
    sa.Column('typeOfDelivery', sa.String(length=100), nullable=True),
    sa.Column('complication_deli', sa.String(length=100), nullable=True),
    sa.Column('birth_weight', sa.String(length=100), nullable=True),
    sa.Column('birth_problem', sa.String(length=100), nullable=True),
    sa.Column('medication', sa.String(length=100), nullable=True),
    sa.Column('immunization', sa.String(length=100), nullable=True),
    sa.Column('effects', sa.String(length=100), nullable=True),
    sa.Column('gms_0', sa.String(length=100), nullable=True),
    sa.Column('gms_1', sa.String(length=100), nullable=True),
    sa.Column('gms_2', sa.String(length=100), nullable=True),
    sa.Column('gms_3', sa.String(length=100), nullable=True),
    sa.Column('gms_4', sa.String(length=100), nullable=True),
    sa.Column('gms_5', sa.String(length=100), nullable=True),
    sa.Column('gms_6', sa.String(length=100), nullable=True),
    sa.Column('gms_7', sa.String(length=100), nullable=True),
    sa.Column('gms_8', sa.String(length=100), nullable=True),
    sa.Column('gms_9', sa.String(length=100), nullable=True),
    sa.Column('gms_10', sa.String(length=100), nullable=True),
    sa.Column('fms_0', sa.String(length=100), nullable=True),
    sa.Column('fms_1', sa.String(length=100), nullable=True),
    sa.Column('fms_2', sa.String(length=100), nullable=True),
    sa.Column('fms_3', sa.String(length=100), nullable=True),
    sa.Column('fms_4', sa.String(length=100), nullable=True),
    sa.Column('fms_5', sa.String(length=100), nullable=True),
    sa.Column('fms_6', sa.String(length=100), nullable=True),
    sa.Column('fms_7', sa.String(length=100), nullable=True),
    sa.Column('fms_8', sa.String(length=100), nullable=True),
    sa.Column('fms_9', sa.String(length=100), nullable=True),
    sa.Column('adl_0', sa.String(length=100), nullable=True),
    sa.Column('adl_1', sa.String(length=100), nullable=True),
    sa.Column('adl_2', sa.String(length=100), nullable=True),
    sa.Column('adl_3', sa.String(length=100), nullable=True),
    sa.Column('adl_4', sa.String(length=100), nullable=True),
    sa.Column('adl_5', sa.String(length=100), nullable=True),
    sa.Column('adl_6', sa.String(length=100), nullable=True),
    sa.Column('cog_0', sa.String(length=100), nullable=True),
    sa.Column('cog_1', sa.String(length=100), nullable=True),
    sa.Column('cog_2', sa.String(length=100), nullable=True),
    sa.Column('cog_3', sa.String(length=100), nullable=True),
    sa.Column('cog_4', sa.String(length=100), nullable=True),
    sa.Column('cog_5', sa.String(length=100), nullable=True),
    sa.Column('cog_6', sa.String(length=100), nullable=True),
    sa.Column('omd_0', sa.String(length=100), nullable=True),
    sa.Column('omd_1', sa.String(length=100), nullable=True),
    sa.Column('omd_2', sa.String(length=100), nullable=True),
    sa.Column('omd_3', sa.String(length=100), nullable=True),
    sa.Column('omd_4', sa.String(length=100), nullable=True),
    sa.Column('omd_5', sa.String(length=100), nullable=True),
    sa.Column('omd_6', sa.String(length=100), nullable=True),
    sa.Column('omd_7', sa.String(length=100), nullable=True),
    sa.Column('omd_8', sa.String(length=100), nullable=True),
    sa.Column('omd_9', sa.String(length=100), nullable=True),
    sa.Column('slp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['slp_id'], ['slp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date_taken', sa.DateTime(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('slp_id', sa.Integer(), nullable=False),
    sa.Column('goal_text', sa.Text(), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=True),
    sa.Column('intervention_text', sa.Text(), nullable=True),
    sa.Column('assessment_result_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_result_id'], ['assessment_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slp_id'], ['slp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lip_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_result_id', sa.Integer(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['assessment_result_id'], ['assessment_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lip_frames')
    op.drop_table('goal')
    op.drop_table('assessment_results')
    op.drop_table('patient')
    op.drop_table('slp')
    # ### end Alembic commands ###
