"""updated goal again

Revision ID: 6e3ee786ae00
Revises: d40f0bac4261
Create Date: 2025-05-28 07:04:47.346318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3ee786ae00'
down_revision = 'd40f0bac4261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('intervention_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('intervention_text')
        batch_op.drop_column('problem_description')

    # ### end Alembic commands ###
