"""Add new fields to Patient model

Revision ID: 73d8c93bc415
Revises: 
Create Date: 2025-05-21 12:54:29.672419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '73d8c93bc415'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('religion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('diagnosis', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('doe', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('precautions', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_medication', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_person', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('alt_contact_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('grade_level', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('father_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('father_contact_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('father_med_history', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mother_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mother_contact_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mother_med_history', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sibling', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sibling_med_history', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('complication_preg', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('med_taken', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('duration_med_taken', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('typeOfDelivery', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('complication_deli', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birth_weight', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birth_problem', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('medication', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('immunization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('effects', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gms_0', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gms_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gms_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gms_3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gms_4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gms_5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gms_6', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gms_7', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gms_8', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gms_9', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gms_10', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fms_0', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fms_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fms_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fms_3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fms_4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fms_5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fms_6', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fms_7', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fms_8', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fms_9', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('adl_0', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('adl_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('adl_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('adl_3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('adl_4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('adl_5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('adl_6', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cog_0', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cog_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cog_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cog_3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cog_4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cog_5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cog_6', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('omd_0', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('omd_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('omd_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('omd_3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('omd_4', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('omd_5', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('omd_6', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('omd_7', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('omd_8', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('omd_9', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('omd_9')
        batch_op.drop_column('omd_8')
        batch_op.drop_column('omd_7')
        batch_op.drop_column('omd_6')
        batch_op.drop_column('omd_5')
        batch_op.drop_column('omd_4')
        batch_op.drop_column('omd_3')
        batch_op.drop_column('omd_2')
        batch_op.drop_column('omd_1')
        batch_op.drop_column('omd_0')
        batch_op.drop_column('cog_6')
        batch_op.drop_column('cog_5')
        batch_op.drop_column('cog_4')
        batch_op.drop_column('cog_3')
        batch_op.drop_column('cog_2')
        batch_op.drop_column('cog_1')
        batch_op.drop_column('cog_0')
        batch_op.drop_column('adl_6')
        batch_op.drop_column('adl_5')
        batch_op.drop_column('adl_4')
        batch_op.drop_column('adl_3')
        batch_op.drop_column('adl_2')
        batch_op.drop_column('adl_1')
        batch_op.drop_column('adl_0')
        batch_op.drop_column('fms_9')
        batch_op.drop_column('fms_8')
        batch_op.drop_column('fms_7')
        batch_op.drop_column('fms_6')
        batch_op.drop_column('fms_5')
        batch_op.drop_column('fms_4')
        batch_op.drop_column('fms_3')
        batch_op.drop_column('fms_2')
        batch_op.drop_column('fms_1')
        batch_op.drop_column('fms_0')
        batch_op.drop_column('gms_10')
        batch_op.drop_column('gms_9')
        batch_op.drop_column('gms_8')
        batch_op.drop_column('gms_7')
        batch_op.drop_column('gms_6')
        batch_op.drop_column('gms_5')
        batch_op.drop_column('gms_4')
        batch_op.drop_column('gms_3')
        batch_op.drop_column('gms_2')
        batch_op.drop_column('gms_1')
        batch_op.drop_column('gms_0')
        batch_op.drop_column('effects')
        batch_op.drop_column('immunization')
        batch_op.drop_column('medication')
        batch_op.drop_column('birth_problem')
        batch_op.drop_column('birth_weight')
        batch_op.drop_column('complication_deli')
        batch_op.drop_column('typeOfDelivery')
        batch_op.drop_column('duration_med_taken')
        batch_op.drop_column('med_taken')
        batch_op.drop_column('complication_preg')
        batch_op.drop_column('sibling_med_history')
        batch_op.drop_column('sibling')
        batch_op.drop_column('mother_med_history')
        batch_op.drop_column('mother_contact_no')
        batch_op.drop_column('mother_name')
        batch_op.drop_column('father_med_history')
        batch_op.drop_column('father_contact_no')
        batch_op.drop_column('father_name')
        batch_op.drop_column('grade_level')
        batch_op.drop_column('alt_contact_no')
        batch_op.drop_column('contact_no')
        batch_op.drop_column('emergency_person')
        batch_op.drop_column('current_medication')
        batch_op.drop_column('precautions')
        batch_op.drop_column('doe')
        batch_op.drop_column('diagnosis')
        batch_op.drop_column('religion')
        batch_op.drop_column('dob')
        batch_op.drop_column('address')
        batch_op.drop_column('sex')
        batch_op.drop_column('age')

    op.create_table('peabody_results',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.Column('date_taken', sa.DATETIME(), nullable=True),
    sa.Column('answers', sqlite.JSON(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_session',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
