"""Add patient_image column to Patient model

Revision ID: d3afc136fbd8
Revises: 5b2a073c7f0d
Create Date: 2025-06-14 08:50:08.971702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3afc136fbd8'
down_revision = '5b2a073c7f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('patient_image')

    # ### end Alembic commands ###
