"""upd goal model

Revision ID: fa5827591ea1
Revises: 29cc3f0d8965
Create Date: 2025-05-27 14:43:27.125783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5827591ea1'
down_revision = '29cc3f0d8965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_result_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_goal_assessment_result_id', 'assessment_results', ['assessment_result_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_goal_assessment_result_id', type_='foreignkey')
        batch_op.drop_column('assessment_result_id')

    # ### end Alembic commands ###
